//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toyzshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlinanUrun
    {
        public int UrunID { get; set; }
        public string UrunAd { get; set; }
        public string UrunKategori { get; set; }
        public Nullable<double> Sirket1 { get; set; }
        public Nullable<double> Sirket2 { get; set; }
        public Nullable<double> Sirket3 { get; set; }
        public Nullable<double> Sirket4 { get; set; }
        public string AlınanSirket { get; set; }
        public double AlınanFiyat { get; set; }
    }
}
