//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toyzshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciYntm
    {
        public int KullaniciID { get; set; }
        public string AdSoyad { get; set; }
        public string Sifre { get; set; }
    }
}
