//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toyzshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int KullaniciID { get; set; }
        public string KullaniciAdSoyad { get; set; }
        public string KullaniciSifre { get; set; }
        public Nullable<int> KullaniciMaas { get; set; }
        public string IzinGunu { get; set; }
    }
}
