//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toyzshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatilanUrun
    {
        public int UrunID { get; set; }
        public string UrunAd { get; set; }
        public string UrunKategori { get; set; }
        public int Stok { get; set; }
        public double Fiyat { get; set; }
        public Nullable<int> İslem { get; set; }
    }
}
